vich_uploader:
    db_driver: orm

    mappings:
        badges:
            uri_prefix: /img/badges
            upload_destination: '%kernel.project_dir%/assets/img/badges'
    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
